spring.application.name=theatre
spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=theatre
spring.datasource.username=theatre
spring.datasource.password=theatre
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=theatre
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
#
#spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
#spring.liquibase.default-schema=theatre

server.port=8080

theatre.reservation-hold-minutes=15
theatre.default-page-size=10
theatre.log-level=INFO
theatre.log-file=logs/theatre.log

logging.level.root=WARN
logging.level.bg.uni.fmi.theatre=INFO