spring.config.activate.on-profile=dev

theatre.log-level=DEBUG
theatre.log-file=logs/theatre-dev.log

logging.level.root=INFO
logging.level.bg.uni.fmi.theatre=DEBUG

spring.ai.ollama.base-url=https://4152-88-203-144-79.ngrok-free.app
spring.ai.ollama.chat.options.model=gemma4
spring.ai.ollama.chat.options.temperature=0.7