spring.config.activate.on-profile=test
spring.jpa.show-sql=false

theatre.log-level=ERROR
theatre.log-file=logs/theatre-test.log

logging.level.root=WARN
logging.level.bg.uni.fmi.theatre=ERROR
logging.level.org.testcontainers=INFO
logging.level.liquibase=WARN